### ISSUE TITLE
EventModel not found error

### ISSUE THREAD

**Issue by grsherwin** [acaronlex/laravel-calendar#10]
I have installed the application.  The app provider and alias did not show-up in the config file.  When I try to execute the sample code I get the EventModel not found.  Can you help?

**Comment by grsherwin** [comment]
I am using Laravel 8

**Comment by acaronlex** [comment]
Hello!

You can just remove it, it's not necessary and I don't remember why is was there.

I've removed it from the doc.

Thanks!
