### ISSUE TITLE
Using obsoleted options

### ISSUE THREAD

**Issue by DanielMalmgren** [acaronlex/laravel-calendar#15]
Hi.
When using Fullcalendar 5 I get the following warnings in my browser console:

Unknown option 'header'
Unknown option 'eventLimit'

Both those options are removed in v5, I guess they should be removed from the default options in laravel-calendar.

**Comment by kobe-ra** [comment]
same problem. should i use version 4 until its fixed?

**Comment by DanielMalmgren** [comment]
Either that or simply ignore the warnings, that's what I did :-)

**Comment by kobe-ra** [comment]
in my case events would not even be displayed on calendar, in fullcalendar 5.8 version, so im moving to vue for this matter.

**Comment by seche** [comment]
@acaronlex can we pull the PR #14 please :)

**Comment by acaronlex** [comment]
It has been merged. Thanks to you!
