### ISSUE TITLE
Events rendered with wrong time zone

### ISSUE THREAD

**Issue by DanielMalmgren** [acaronlex/laravel-calendar#17]
I keep all event times in my system in local time, like this: "2021-04-06T04:00". However in my fullcalendar they turn up two hours wrong (I'm in Sweden and currently it's DST) and after some digging I discovered it's because laravel-calendar appends "+00:00" to the end of the start and end time of all my events, so fullcalendar interprets them as being UTC. Ie the example above is rendered as "2021-04-06T04:00:00+00:00".

According to https://fullcalendar.io/docs/timeZone, a time stamp with no time zone information is interpreted as being a local time, which is what I want to happen. Is this a bug or me thinking wrong?

It doesn't matter if I use seconds or not (ie "2021-04-06T04:00" vs "2021-04-06T04:00:00"). The only workaround I've found so far is adding "+02:00" to the end, which kinda works for the time being but is really ugly.

**Comment by MrX123123** [comment]
Hi DanielMalmgren,
you are not alone, same issue for me. I am facing also a two hours offset as you.
Sounds like a bug to me, too.

Br
Jan
