### ISSUE TITLE
readme.md - no 'use' section for class used in example 

### ISSUE THREAD

**Issue by proliteweb** [acaronlex/laravel-calendar#18]
$calendar = new **Calendar**();
        $calendar->addEvents($events)...
Example doesn't have namespace, which results in an error in the example 
![photo_2021-04-11_03-03-10](https://user-images.githubusercontent.com/19736863/114287790-7b44fc80-9a72-11eb-940e-b5b37553263c.jpg)

**Comment by GreatWhiteDan** [comment]
I was able to resolve this by adding 
use Acaronlex\LaravelCalendar\Calendar;

Hope that helps
