### ISSUE TITLE
The FullCalendar view "dayGridMonth" does not exist

### ISSUE THREAD

**Issue by mrhili** [acaronlex/laravel-calendar#2]
jquery-3.5.1.min.js:2 Uncaught Error: The FullCalendar view "dayGridMonth" does not exist. Make sure your plugins are loaded correctly.

CONTROLLER

public function cal()
    {

        $events = [];
        
        $events[] = \Calendar::event(
            "Valentine's Day", //event title
            true, //full day event?
            Carbon::now(), //start time (you can also use Carbon instead of DateTime)
            Carbon::now()->addHour(), //end time (you can also use Carbon instead of DateTime)
            'stringEventId' //optionally, you can specify an event ID
        );
        
    
        
        $calendar = \Calendar::addEvents($events)->setOptions([ //set fullcalendar options
            'firstDay' => 1,
            'plugins'=> [ 'dayGridPlugin' ],
            'defaultView'=> 'dayGridMonth',
            'header' => [ 'left'=> 'prev,next', 'center'=> 'title', 'right'=> 'dayGridDay,dayGridWeek,dayGridMonth']
        ])->setCallbacks([ //set fullcalendar callback options (will not be JSON encoded)
            'viewRender' => 'function() {alert("Callbacks!");}'
        ]);

        return view('guardies.cal', compact('calendar'));

    }

VIEW

<!doctype html>
<html lang="en">
<head>
    	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    	<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/main.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.4.0/main.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.4.0/main.min.js"></script>

    	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.4.0/main.min.css"/>

    <style>
        /* ... */
    </style>
</head>
<body>
    {!! $calendar->calendar() !!}
    {!! $calendar->script() !!}
</body>
</html>

-----------------------
I updated it

**Comment by acaronlex** [comment]
In your controller, your plugins should be like this

`'plugins'=> [ 'dayGrid' ],`

**Comment by mrhili** [comment]
Thank you it works i hope that you upgrade the readme file one day to be easier to use.
