### ISSUE TITLE
How to use custom button

### ISSUE THREAD

**Issue by gborgonovo** [acaronlex/laravel-calendar#21]
How can I add a custom button to the header?

I have seen I can add the custom button 
```
customButtons: {
  myCustomButton: {
    text: 'custom!',
    click: function() {
      alert('clicked the custom button!');
    }
  }
},
```

But I cannot add the click callback.

I imagine I must add it in here 
```
$calendar->setCallbacks([
    'select' => 'function(selectionInfo){}',
    'eventClick' => 'function(event){}'
]);
```
but I cannot understand how.

Thank you for any hint.

**Comment by seche** [comment]
Although I will be creating a PR, Custom buttons don't currently work because the callback function is outputted as a string and not being picked up by FullCalendar.

This is how I set it up on my calendar object:

```
$calendar->setOptions([
            'customButtons' => [
                'myCustomButton' => [
                    'text'=> 'custom!',
                    'click' => 'function() {
                                alert(\'clicked the custom button!\');
                            }'
                ]
            ]
        ]);
```

But will need the `replaceKeys `function from my PR to make it work.

**Comment by acaronlex** [comment]
Thanks @seche four your contribution!
