### ISSUE TITLE
No available FullCalendar view plugins.

### ISSUE THREAD

**Issue by rslanzi** [acaronlex/laravel-calendar#4]
Following your example "Sample View", I get this error: 
`Error: No available FullCalendar view plugins.`

Looking into console, the row that fire the error is this: 
`var calendar = new FullCalendar.Calendar(calendarEl);`

I tried to update cdn script to 4.4.2 but nothing changed. Also loading JS files from locale.

Any idea?

**Comment by amousavii** [comment]
Same issue with FC v.2.2.7
