### ISSUE TITLE
Class 'Acaronlex\LaravelCalendar\ServiceProvider' not found

### ISSUE THREAD

**Issue by Dzemy** [acaronlex/laravel-calendar#7]
```
In ProviderRepository.php line 208:

  Class 'Acaronlex\LaravelCalendar\ServiceProvider' not found


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by jeremykenedy** [comment]
This PR will fix it:

https://github.com/GrandpaFizz/laravel-calendar/pull/5

**Comment by jeremykenedy** [comment]
Until the PR is accepted change 

`"acaronlex/laravel-calendar": "^1.2",` to `"acaronlex/laravel-calendar": "^2.0",`

And add the following to call the fork with the fix in the mean time:

```
    "repositories": [
        {
            "type": "vcs",
            "url":  "https://github.com/jeremykenedy/laravel-calendar.git"
        }
    ],
```

**Comment by eperezf** [comment]
Tried modifying to 2.0 and adding the repository to composer.json but the error persists

**Comment by musafir928** [comment]
you may need to run: composer update

**Comment by acaronlex** [comment]
Merged.

**Comment by BbyJlyn0714** [comment]
![image](https://user-images.githubusercontent.com/77874830/105940934-4c380500-6097-11eb-823f-b3cc04e789e3.png)

Acaronlex is not working in my sid. how to fix it ?
