### ISSUE TITLE
 Uncaught ReferenceError: FullCalendar is not defined

### ISSUE THREAD

**Issue by har0ld1** [acaronlex/laravel-calendar#9]
Hello, 

I have a problem using the calendar. Thank you in advance for your answer! 

![image](https://user-images.githubusercontent.com/22529533/101835189-b292b380-3b3b-11eb-9556-d54f681fc1c0.png)
![image](https://user-images.githubusercontent.com/22529533/101835050-7bbc9d80-3b3b-11eb-9878-ddeb7b897a43.png)
![image](https://user-images.githubusercontent.com/22529533/101835293-d9e98080-3b3b-11eb-9444-48bc81f55fdb.png)

**Comment by acaronlex** [comment]
You seem to include jQuery two times. Can you remove one link ?

**Comment by acaronlex** [comment]
Hello!

I've just tested it and jsdeliver seems to have updated their scripts. So I've updated the doc for the new scripts, you can use them! 😄 

#acx
